logging:
  level:
    com.rodemtree.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.security: DEBUG

spring:
  application:
    name: yeyak-itda
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

jwt:
  secret: ${JWT_SECRET}
  expiration:
    access: 3600000
